In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4]
x = np.array(lista)
print(type(x))

<class 'numpy.ndarray'>


In [3]:
print(x,lista)
#los arreglos tienen como una forma de matriz de n dimensiones
#en cambio las listas son tratados como vectores

[1 2 3 4] [1, 2, 3, 4]


In [4]:
print(3*x,3*lista)
#arreglo multiplica por 3 y la lista la repite 3 veces
#para los arreglos pasa con cualquier tipo de operación que se le realice
#ya sea multiplicación, división, suma, etc

[ 3  6  9 12] [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [6]:
print(np.sin(x))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [7]:
x = np.arange(10,100,2)
print(x)
print(type(x))
#función que se parece al range de python en este caso nos presenta el de numpy
#el 100 no es incluido (desde,hasta,paso)
#los pasos también pueden ser negativos, pero las cotas tienen que invertirse

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58
 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
<class 'numpy.ndarray'>


In [10]:
y = np.linspace(0,10,100)
print(y)
print(len(y))
#(desde,hasta,número de elementos)
#si le agregamos un ? nos dará una ayuda, o poner help(lo que se pregunta), ship y tab

[  0.           0.1010101    0.2020202    0.3030303    0.4040404
   0.50505051   0.60606061   0.70707071   0.80808081   0.90909091
   1.01010101   1.11111111   1.21212121   1.31313131   1.41414141
   1.51515152   1.61616162   1.71717172   1.81818182   1.91919192
   2.02020202   2.12121212   2.22222222   2.32323232   2.42424242
   2.52525253   2.62626263   2.72727273   2.82828283   2.92929293
   3.03030303   3.13131313   3.23232323   3.33333333   3.43434343
   3.53535354   3.63636364   3.73737374   3.83838384   3.93939394
   4.04040404   4.14141414   4.24242424   4.34343434   4.44444444
   4.54545455   4.64646465   4.74747475   4.84848485   4.94949495
   5.05050505   5.15151515   5.25252525   5.35353535   5.45454545
   5.55555556   5.65656566   5.75757576   5.85858586   5.95959596
   6.06060606   6.16161616   6.26262626   6.36363636   6.46464646
   6.56565657   6.66666667   6.76767677   6.86868687   6.96969697
   7.07070707   7.17171717   7.27272727   7.37373737   7.47474747
   7.575757

In [11]:
z = np.zeros(5)
print(z)
#arreglo sólo de ceros
#se puede hacer con matrices tambien

[ 0.  0.  0.  0.  0.]


In [13]:
a = np.ones([3,4])
print(a)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [21]:
w = np.random.random((4,3))
print(w)
#ejecuta números random

[[ 0.14840292  0.90399903  0.81199024]
 [ 0.6320434   0.14614544  0.00638343]
 [ 0.34450408  0.37739894  0.7125347 ]
 [ 0.78116137  0.69153102  0.90531625]]


In [22]:
np.random.randint(7)
#imprime números al azar enteros, menores que 7

6

In [26]:
x = np.random.randint(1,11, size=100)
print(x)
#100 números random desde 1 hasta el 10

[ 9  3  1  4  7  7 10  7  2  2  6  9  5  3  2  2  7  7  4  1  5  3  7  4  2
  2  8  2  6  3  7  5  6  2  4 10  3  5  7  2  8  4  3  1 10  5  2  8 10  8
  9  8  4  4  6  3 10  2  8  6  4  6 10  3  9  3  4  2  9  3  9  3 10  7  4
  8  7  1  4  6  4  7  1  6  2  1  6  3  4  7  9  2  6  9  9  1  3  1  5  7]


In [28]:
np.where(x==3)[0]
#donde x=3


array([ 1, 13, 21, 29, 36, 42, 55, 63, 65, 69, 71, 87, 96])

In [29]:
x==3

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
        True, False,  True, False, False, False,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False,  True, False, False, False], dtype=bool)

In [30]:
np.count_nonzero(x==3)
#cuantas veces x=3

13

In [31]:
np.max(x)
#número máximo

10

In [38]:
data = np.genfromtxt?


In [41]:
data = np.genfromtxt('datos.txt')
print(data)
print(np.shape(data))

[[ 0.1    0.738]
 [ 0.25   0.826]
 [ 0.41   0.981]
 [ 0.56   0.974]
 [ 0.71   0.915]
 [ 0.86   0.897]
 [ 1.02   0.739]
 [ 1.17   0.785]
 [ 1.32   0.635]
 [ 1.47   0.52 ]
 [ 1.63   0.49 ]
 [ 1.78   0.428]
 [ 1.93   0.497]
 [ 2.08   0.355]
 [ 2.24   0.359]
 [ 2.39   0.328]
 [ 2.54   0.44 ]
 [ 2.69   0.441]
 [ 2.85   0.433]
 [ 3.     0.419]]
(20, 2)


In [42]:
c1 = data[:,0]
print(c1)
#imprime la primera columna

[ 0.1   0.25  0.41  0.56  0.71  0.86  1.02  1.17  1.32  1.47  1.63  1.78
  1.93  2.08  2.24  2.39  2.54  2.69  2.85  3.  ]


In [44]:
c2 = data[:,1]
print(c2)
#imprime la segunda columna

[ 0.738  0.826  0.981  0.974  0.915  0.897  0.739  0.785  0.635  0.52   0.49
  0.428  0.497  0.355  0.359  0.328  0.44   0.441  0.433  0.419]


In [45]:
print(np.max(c2))

0.981


In [46]:
print(np.mean(c1))
#est6e es el promedio

1.55


In [48]:
d = np.genfromtxt('stockholm_td_adj.dat')
#datos de la temperatura de estocolmo

In [50]:
print(d)
print(np.shape(d))

[[  1.80000000e+03   1.00000000e+00   1.00000000e+00 ...,  -6.10000000e+00
   -6.10000000e+00   1.00000000e+00]
 [  1.80000000e+03   1.00000000e+00   2.00000000e+00 ...,  -1.54000000e+01
   -1.54000000e+01   1.00000000e+00]
 [  1.80000000e+03   1.00000000e+00   3.00000000e+00 ...,  -1.50000000e+01
   -1.50000000e+01   1.00000000e+00]
 ..., 
 [  2.01100000e+03   1.20000000e+01   2.90000000e+01 ...,   4.20000000e+00
    4.20000000e+00   1.00000000e+00]
 [  2.01100000e+03   1.20000000e+01   3.00000000e+01 ...,  -1.00000000e-01
   -1.00000000e-01   1.00000000e+00]
 [  2.01100000e+03   1.20000000e+01   3.10000000e+01 ...,  -3.30000000e+00
   -3.30000000e+00   1.00000000e+00]]
(77431, 7)
