In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x = np.array([1,2,3,4]) 
y = np.array([1,4,9,16]) 
#Estos son arreglos en este caso sería un arreglo unidimensional, un vector
#Ejemplos de estas cosas de numpy se puede ver archivo GitHub 
#las dimensiones se ven con las comas dentro del parentesis
#El corchete es una lista dentro de un array

In [4]:
print(x)

[1 2 3 4]


In [5]:
x
#nos muestra el tipo de variable que es junto con su valor

array([1, 2, 3, 4])

In [9]:
print(np.shape(x))
#(cantidad de elemtos que hay, dimensión)
print(len(x))
#Cantidad de elementos que hay
print(type(x))

(4,)
4
<class 'numpy.ndarray'>


In [8]:
l = [1,2,3,4]
print(l)
print(type(l))

[1, 2, 3, 4]
<class 'list'>


In [10]:
print(2*x)
#Multiplica por 2 cada elemento de x, aquí se puede realizar con números enteros y decimales
print(2*l)
#Nos repite 2 veces la lista, esto solo aplica para números enteros

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


In [13]:
m = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(m)
print(np.shape(m))
#Aquí nos imprime(filas,columnas)
print(len(m))
#Imprime la cantidad de lsitas qeu hay en un arreglo

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4


In [14]:
print(3.4*m)
#Multiplica cadqa elemento ppor 3.5 es lo mismo que en el caso anterios con x
#Exepto que aquí se presenta con una matriz

[[  3.4   6.8  10.2]
 [ 13.6  17.   20.4]
 [ 23.8  27.2  30.6]
 [ 34.   37.4  40.8]]


In [16]:
print(x)
print(x[2])
#Imprime el 3er elemento porque los índices comienzan con el 0
print(x[-1])
#Imprime el último elemento

[1 2 3 4]
3
4


In [17]:
for i in range(len(x)):
    print(x[i])
#Imprime los elemetos que están dentro de la lista del arreglo x en el rango de la misma
#Esto significa que el rango es de 0 a 3

1
2
3
4


In [18]:
print(m)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
print(m[1,2])
#en la matriz baja 1 y para el lado 2 (recordemos que los indices comienzan desde el 0)

6


In [21]:
print(x)
print(x[0:2:1])
#desde:hasta:paso
#el hasta en todos los casos son no incluidos se comporta como un intervalo abierto

[1 2 3 4]
[1 2]


In [25]:
print(m)
print(m[1:3])
print(m[1:])
print(m[1:3,1:])
#Desde que fila hasta cual, desde qeu columna hasta cual
#las filas son para los lados, las columnas son hacia abajo
#[primera fila desde:hasta, segunda fila desde:hasta]
#en el primer caso imprime el 5 con el 8 y con la coma la otra dimensión imprime el 6 con el 9

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[5 6]
 [8 9]]


In [26]:
m2 = m[1:3,1:]
print(type(m2))
print(m2)
print(np.shape(m2))
#la matriz resultante es una matriz de 2x2

<class 'numpy.ndarray'>
[[5 6]
 [8 9]]
(2, 2)


In [28]:
print(m[:,1])
#solo la segunda columna
print(m[-1,:])
#solo la última fila


[ 2  5  8 11]
[10 11 12]
